version: "3"

services:
  mysql-database-service:
    image: mysql
    container_name: mysql-container
    ports:
      - "3307:3306"
    networks: [ foodie-app-network ]
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  mongo-database-service:
    image: mongo
    container_name: mongodb-database-container
    ports:
      - "27018:27017"
    networks: [ foodie-app-network ]

  customer-auth-service:
    build: /customer-auth
    container_name: customer-auth-service-container
    ports:
      - "8081:8081"
    networks: [ foodie-app-network ]
    depends_on: [ mysql-database-service ]
    restart: always

networks:
  foodie-app-network:
    driver: bridge