server:
  port: 8082
  error:
    include-message: always

spring:
  application:
    name: customer-service

  data:
    mongodb:
      uri: mongodb://mongodb-database-container:27017/customer
      port: 27017
      database: customer

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka
