server:
  port: 8083
  error:
    include-message: always

spring:
  application:
    name: restaurant-service

  data:
    mongodb:
      uri: mongodb://mongodb-database-container:27017/restaurant
      port: 27017
      database: restaurant
